Viesbutis/Models/KambarysPosisteme/KambarioTipas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Viesbutis.Models.KambarysPosisteme
{
    public class KambarioTipas
    {

        public int ID { get; set; }

       [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Kambario tipas (trumpinys)")]
       [StringLength(50, MinimumLength = 3)]
        public string trumpinys { get; set; }

        [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Kambario tipas")]
        [StringLength(50, MinimumLength = 3)]
        public string pavadinimas { get; set; }

       [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Parašymas")]
       [StringLength(500, MinimumLength = 3)]
        public string aprasymas { get; set; }
        public virtual ICollection<Kambarys> Kambariai { get; set; }
    }
}

Viesbutis/Models/RezervacijaPosisteme/Rezervacija.cs
using System;
using System.Collections.Generic;
using Viesbutis.Models.KambarysPosisteme;
using Viesbutis.Models.KlientasPosisteme;
using Viesbutis.Models.MokejimasPosisteme;

namespace Viesbutis.Models.RezervacijaPosisteme
{
    public class Rezervacija
    {
        public int ID { get; set; }
        public int klientasID { get; set; }
        public int mokejimasID { get; set; }
        public int kambarysID { get; set; }
        public int rezervacijoslaikasID { get; set; }
        public Boolean patvirtinta { get; set; }

        public virtual Klientas Klientas { get; set; }
        public virtual Mokejimas Mokejimas { get; set; }
        public virtual Kambarys Kambarys { get; set; }
        public virtual RezervacijosLaikas RezervacijosLaikas { get; set; }
        public virtual ICollection<PaslaugosTarpine> PaslaugosTarpines { get; set; }

    }
}

Viesbutis/Controllers/KambarioTipasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viesbutis.Models.KambarysPosisteme;
using Viesbutis.DAL;

namespace Viesbutis.Controllers
{
    public class KambarioTipasController : Controller
    {
        private ViesbutisContext db = new ViesbutisContext();

        [Authorize(Roles = "Administratorius")]
        public ActionResult Index()
        {
            return View(db.KambarioTipai.ToList());
        }



       [Authorize(Roles = "Administratorius")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administratorius")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,trumpinys,pavadinimas,aprasymas")] KambarioTipas kambariotipas)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool pasikartojapav = db.KambarioTipai.Where(model => model.pavadinimas == kambariotipas.pavadinimas ||
                        model.trumpinys == kambariotipas.trumpinys).Any();
                    if (pasikartojapav)
                    {
                        ViewBag.ErrorMessage = "Kambario tipas su tokiu pavadinimu/ trumpiniu jau egzistuoja.";
                    }
                    else
                    {
                        db.KambarioTipai.Add(kambariotipas);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Neįmanoma išsaugoti pakeitimų. Pamėginkite dar kartą ir jei nepavyks susisiekite sus sistemos administratoriumi.");
            }

            return View(kambariotipas);
        }

        [Authorize(Roles = "Administratorius")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KambarioTipas kambariotipas = db.KambarioTipai.Find(id);
            if (kambariotipas == null)
            {
                return HttpNotFound();
            }
            return View(kambariotipas);
        }

        [Authorize(Roles = "Administratorius")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,trumpinys,pavadinimas,aprasymas")] KambarioTipas kambariotipas)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(kambariotipas).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            
           catch (DataException /* dex */)
           {
              //Log the error (uncomment dex variable name and add a line here to write a log.
              ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
           }
            return View(kambariotipas);
        }

       [Authorize(Roles = "Administratorius")]
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Ištrinti nepavyko.Try again, and if the problem persists see your system administrator.";
            }
            KambarioTipas kambariotipas = db.KambarioTipai.Find(id);
            if (kambariotipas == null)
            {
                return HttpNotFound();
            }
            return View(kambariotipas);
        }

       [Authorize(Roles = "Administratorius")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                KambarioTipas kambariotipas = db.KambarioTipai.Find(id);
                bool panaudotas = db.Kambariai.Where(model => model.kambarioTipasID== id).Any();
                if (panaudotas)
                {
                    ViewBag.ErrorMessage = "Yra kambarys su tokiu tipu.";
                    return View(kambariotipas);
                }
                db.KambarioTipai.Remove(kambariotipas);
                db.SaveChanges();
              
            }
            catch (DataException/* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administratorius")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viesbutis/Controllers/RezervacijaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viesbutis.Models.RezervacijaPosisteme;
using Viesbutis.DAL;
using System.Data.Entity.Infrastructure;

namespace Viesbutis.Controllers
{
    public class RezervacijaController : Controller
    {
        private ViesbutisContext db = new ViesbutisContext();

        // GET: /Rezervacija/
        public ActionResult Index()
        {
            //var rezervacijos = db.Rezervacijos.Include(r => r.Kambarys).Include(r => r.Klientas).Include(r => r.Mokejimas).Include(r => r.RezervacijosLaikas);
            //return View(rezervacijos.ToList());
            string teises = db.Klientai.Where(model => model.prisijungimo_vardas == User.Identity.Name).FirstOrDefault().teises;
            int id = db.Klientai.Where(model => model.prisijungimo_vardas == User.Identity.Name).FirstOrDefault().ID;
            var rezervacijos = db.Rezervacijos.Include(r => r.Kambarys).Include(r => r.Klientas).Include(r => r.Mokejimas).Include(r => r.RezervacijosLaikas);
            if (teises.Equals("Klientas")) return View(rezervacijos.ToList().Where(s => s.klientasID == id));
            else return View(rezervacijos.ToList());
        }

        // GET: /Rezervacija/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.Rezervacijos.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // GET: /Rezervacija/Create
        // KEICIAU ----- gAUNA ID - KAMBARIO, KURIS REZERVUOJAMAS ID
        public ActionResult Create(int id)
        {
            //-------KEICIAU-------------
            ViewBag.kambarysID = id;

            //---------KEICIAU-------------------------
            // iskart pasiima userID, kuris rezervuojasi
            int userID = db.Klientai.Where(model => model.prisijungimo_vardas == User.Identity.Name).FirstOrDefault().ID;
            ViewBag.klientasID = userID;
            //ViewBag.klientasID = new SelectList(db.Klientai, "ID", "vardas");
            //-----------------------------------------

            //--------KEICIAU------------------------------
            // Duoda pasirinkt tik is tu laiku, kurie susieti su kambariu, kurio id perduodamas ir kurie nera uzimti;    
            ViewBag.rezervacijoslaikasID = new SelectList(db.RezervacijosLaikai.Where(model => model.kambarysID == id && model.uzimta == false), "ID", "rezervuota_nuo_iki");
            //ViewBag.rezervacijoslaikasID = new SelectList(db.RezervacijosLaikai, "ID", "ID");
            //----------------------------------------------

            return View();
        }

        // POST: /Rezervacija/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "klientasID,kambarysID,rezervacijoslaikasID,patvirtinta")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {

                List<Viesbutis.Models.MokejimasPosisteme.Mokejimas> Mokejimai = db.Mokejimai.ToList();
                List<Viesbutis.Models.KambarysPosisteme.Kambarys> Kambariai = db.Kambariai.ToList();
                List<Viesbutis.Models.MokejimasPosisteme.MokejimoTipas> MokTipas = db.MokejimoTipai.ToList();
                List<Viesbutis.Models.MokejimasPosisteme.MokejimoValiuta> MokValiuta = db.MokejimoValiutos.ToList();

                Viesbutis.Models.MokejimasPosisteme.Mokejimas mokejimas = new Models.MokejimasPosisteme.Mokejimas();
                //if (Mokejimai.Count == 0) mokejimas.ID = 1;
                //else mokejimas.ID = Mokejimai[Mokejimai.Count - 1].ID + 1;
                mokejimas.kas_aptarnavo = "Automatinė sistema";

                int userID = db.Klientai.Where(model => model.prisijungimo_vardas == User.Identity.Name).FirstOrDefault().ID;
                mokejimas.klientas = db.Klientai.Find(userID).vardas + " " + db.Klientai.Find(userID).pavarde;

                mokejimas.mokejimo_busena = false;
                mokejimas.mokejimo_data = DateTime.Now;
                for (int i = 0; i < Kambariai.Count; i++)
                    if (Kambariai[i].ID == rezervacija.kambarysID)
                        mokejimas.mokejimo_suma = Kambariai[i].kaina;
                mokejimas.MokejimoTipas = MokTipas[0];
                mokejimas.mokejimotipasID = MokTipas[0].ID;
                mokejimas.MokejimoValiuta = MokValiuta[0];
                mokejimas.mokejimovaliutaID = MokValiuta[0].ID;
                db.Mokejimai.Add(mokejimas);
                db.SaveChanges();

                rezervacija.mokejimasID = mokejimas.ID;
                db.Rezervacijos.Add(rezervacija);

                RezervacijosLaikas rezlaikas = db.RezervacijosLaikai.Find(rezervacija.rezervacijoslaikasID);
                rezlaikas.uzimta = true;
                db.Entry(rezlaikas).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.kambarysID = rezervacija.kambarysID;
            ViewBag.klientasID = new SelectList(db.Klientai, "ID", "vardas", rezervacija.klientasID);
            ViewBag.mokejimasID = rezervacija.mokejimasID;//new SelectList(db.Mokejimai, "ID", "ID", rezervacija.mokejimasID);
            ViewBag.rezervacijoslaikasID = new SelectList(db.RezervacijosLaikai, "ID", "rezervuota_nuo_iki", rezervacija.rezervacijoslaikasID);
            return View(rezervacija);
        }

        [Authorize(Roles = "Administratorius")]
        // GET: /Rezervacija/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.Rezervacijos.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            //ViewBag.kambarysID = new SelectList(db.Kambariai, "ID", "ID", rezervacija.kambarysID);
            //ViewBag.klientasID = new SelectList(db.Klientai, "ID", "vardas", rezervacija.klientasID);
            //ViewBag.mokejimasID = new SelectList(db.Mokejimai, "ID", "ID", rezervacija.mokejimasID);
            //ViewBag.rezervacijoslaikasID = new SelectList(db.RezervacijosLaikai, "ID", "rezervuota_nuo_iki", rezervacija.rezervacijoslaikasID);
            return View(rezervacija);
        }

        // POST: /Rezervacija/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administratorius")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,patvirtinta")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                var rez = db.Rezervacijos.Find(rezervacija.ID);
                rez.patvirtinta = rezervacija.patvirtinta;

                db.Entry(rez).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.kambarysID = new SelectList(db.Kambariai, "ID", "ID", rezervacija.kambarysID);
            //ViewBag.klientasID = new SelectList(db.Klientai, "ID", "vardas", rezervacija.klientasID);
            //ViewBag.mokejimasID = new SelectList(db.Mokejimai, "ID", "ID", rezervacija.mokejimasID);
            //ViewBag.rezervacijoslaikasID = new SelectList(db.RezervacijosLaikai, "ID", "rezervuota_nuo_iki", rezervacija.rezervacijoslaikasID);
            return View(rezervacija);
        }

        // GET: /Rezervacija/Delete/5
        [Authorize(Roles = "Administratorius,Klientas")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.Rezervacijos.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        [Authorize(Roles = "Administratorius,Klientas")]
        // POST: /Rezervacija/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rezervacija rezervacija = db.Rezervacijos.Find(id);
            db.Rezervacijos.Remove(rezervacija);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administratorius,Klientas")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viesbutis/Views/KambarioTipas/Rezervacija/Create.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Rezervacija

@{
    ViewBag.Title = "Nauja";
}

<h2>Kurti naują rezervaciją</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Rezervacija</h4>
        <hr />
        @Html.ValidationSummary(true)

        @* GAUNAMI KAMBARIO ID IR KLIENTO ID *@
        <input type="hidden" value="@ViewBag.kambarysID" name="kambarysID">
        <input type="hidden" value="@ViewBag.klientasID" name="klientasID">
        <input type="hidden" value="@ViewBag.mokejimasID" name="mokejimasID">
        <input type="hidden" value="false" name="patvirtinta">

        @*  UZKOMENTAVAU, NES AUTOMATISKAI PERDUODA
                <div class="form-group">
                @Html.LabelFor(model => model.klientasID, "Kliento ID", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("klientasID", String.Empty)
                    @Html.ValidationMessageFor(model => model.klientasID)
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.mokejimasID, "Mokėjimo ID", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("mokejimasID", String.Empty)
                    @Html.ValidationMessageFor(model => model.mokejimasID)
                </div>
            </div>*@

        @* UZKOMENTAVAU NES AUTOMATISKAI PERDUODA
                <div class="form-group">
                @Html.LabelFor(model => model.kambarysID, "Kambario ID", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("kambarysID", String.Empty)
                    @Html.ValidationMessageFor(model => model.kambarysID)
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.rezervacijoslaikasID, "Rezervacijos laikas nuo - iki", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("rezervacijoslaikasID", String.Empty)
                @Html.ValidationMessageFor(model => model.rezervacijoslaikasID)
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.patvirtinta, "Rezervacija patvirtinta" , new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.patvirtinta)
                    @Html.ValidationMessageFor(model => model.patvirtinta)
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kurti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į rezervacijų sąrašą", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Viesbutis/Views/KambarioTipas/Rezervacija/Delete.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Rezervacija

@{
    ViewBag.Title = "Ištrinti";
}

<h2>Ištrinti</h2>

<h3>Ar tikrai norite ištrinti šį įrašą?</h3>
<div>
    <h4>Rezervacija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> Kambario aukštas ir numeris  </dt>
        <dd> @Html.DisplayFor(model => model.Kambarys.aukstas) / @Html.DisplayFor(model => model.Kambarys.numeris) </dd>
        <dt> Klientas </dt>
        <dd> @Html.DisplayFor(model => model.Klientas.vardas) @Html.DisplayFor(model => model.Klientas.pavarde) </dd>
        <dt> Rezervuota nuo </dt>
        <dd> @Html.DisplayFor(model => model.RezervacijosLaikas.rezervuota_nuo) </dd>
        <dt> Rezervuota iki </dt>
        <dd> @Html.DisplayFor(model => model.RezervacijosLaikas.rezervuota_iki) </dd>
        <dt> Rezervacija patvirtinta </dt>
        <dd> @Html.DisplayFor(model => model.patvirtinta) </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ištrinti" class="btn btn-default" /> |
            @Html.ActionLink("Sugrįžti į sąrašą", "Index")
        </div>
    }
</div>

Viesbutis/Views/KambarioTipas/Rezervacija/Details.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Rezervacija

@{
    ViewBag.Title = "Informacija";
}

<h2>Informacija apie rezervaciją</h2>

<div>
    <h4>Rezervacija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> Kambario aukštas ir numeris  </dt>
        <dd> @Html.DisplayFor(model => model.Kambarys.aukstas) / @Html.DisplayFor(model => model.Kambarys.numeris) </dd>
        <dt> Klientas </dt>
        <dd> @Html.DisplayFor(model => model.Klientas.vardas) @Html.DisplayFor(model => model.Klientas.pavarde) </dd>
        <dt> Rezervuota nuo </dt>
        <dd> @Html.DisplayFor(model => model.RezervacijosLaikas.rezervuota_nuo) </dd>
        <dt> Rezervuota iki </dt>
        <dd> @Html.DisplayFor(model => model.RezervacijosLaikas.rezervuota_iki) </dd>
        <dt> Rezervacija patvirtinta </dt>
        <dd> @Html.DisplayFor(model => model.patvirtinta) </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Redaguoti", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Grįžti į rezervacijų sąrašą", "Index")
</p>

Viesbutis/Views/KambarioTipas/Rezervacija/Edit.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Rezervacija

@{
    ViewBag.Title = "Redaguoti";
}

<h2>Redaguoti rezervacijos informaciją</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Rezervacija</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.klientasID, "Kliento ID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("klientasID", String.Empty)
                @Html.ValidationMessageFor(model => model.klientasID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mokejimasID, "Mokėjimo ID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("mokejimasID", String.Empty)
                @Html.ValidationMessageFor(model => model.mokejimasID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kambarysID, "Kambario ID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("kambarysID", String.Empty)
                @Html.ValidationMessageFor(model => model.kambarysID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rezervacijoslaikasID, "Rezervacijos laikas nuo - iki", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("rezervacijoslaikasID", String.Empty)
                @Html.ValidationMessageFor(model => model.rezervacijoslaikasID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patvirtinta, "Rezervacija patvirtinta", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patvirtinta)
                @Html.ValidationMessageFor(model => model.patvirtinta)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Išsaugoti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į rezervacijų sąrašą", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Viesbutis/Views/KambarioTipas/Rezervacija/Index.cshtml
@model IEnumerable<Viesbutis.Models.RezervacijaPosisteme.Rezervacija>

@{
    ViewBag.Title = "Rezervacijos";
}

<h2>Rezervacijos</h2>

@* UZKOMENTAVAU, NES REZERVUOJAMA BUS TIK IS KAMBARIU PUSLAPIO PASPAUDUS PRIE NORIMO KAMBARIO REZERVUOTI
        <p>
        <input type="button" class="btn btn-default" value="Nauja" onclick="@("window.location.href='" + @Url.Action("Create", "Rezervacija") + "'");" />
    </p>*@

<table class="table">
    <tr>
        <th> Kambario aukštas / numeris </th>
        <th> Klientas </th>
        <th> Kambarys rezervuotas nuo </th>
        <th> Kambarys rezervuotas iki </th>
        <th> Rezervacija patvirtinta </th>
        <th class="center"> Informacija </th>
        <th class="center"> Redaguoti </th>
        <th class="center"> Ištrinti </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td> @Html.DisplayFor(modelItem => item.Kambarys.aukstas) / @Html.DisplayFor(modelItem => item.Kambarys.numeris) </td>
            <td> @Html.DisplayFor(modelItem => item.Klientas.vardas) @Html.DisplayFor(modelItem => item.Klientas.pavarde) </td>
            <td> @Html.DisplayFor(modelItem => item.RezervacijosLaikas.rezervuota_nuo) </td>
            <td> @Html.DisplayFor(modelItem => item.RezervacijosLaikas.rezervuota_iki) </td>
            <td> @Html.DisplayFor(modelItem => item.patvirtinta) </td>
            <td class="center">
                <a href="@Url.Action("Details", new { id = item.ID })">
                    <i class="glyphicon glyphicon-info-sign"></i>
                </a>
            </td>
            <td class="center">
                <a href="@Url.Action("Edit", new { id = item.ID })">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </td>
            <td class="center">
                <a href="@Url.Action("Delete", new { id = item.ID })">
                    <i class="glyphicon glyphicon-remove"></i>
                </a>
            </td>
        </tr>
    }

</table>