Viesbutis/Models/RezervacijaPosisteme/Paslauga.cs
using System;
using System.Collections.Generic;

namespace Viesbutis.Models.RezervacijaPosisteme
{
    public class Paslauga
    {

        public int ID { get; set; }
        public string pavadinimas { get; set; }
        public string aprasymas { get; set; }
        public double kaina { get; set; }
        public virtual ICollection<PaslaugosTarpine> PaslaugosTarpines { get; set; }

    }
}

Viesbutis/Controllers/PaslaugasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viesbutis.DAL;
using Viesbutis.Models.RezervacijaPosisteme;

namespace Viesbutis.Controllers
{
    public class PaslaugasController : Controller
    {
        private ViesbutisContext db = new ViesbutisContext();

        // GET: Paslaugas
        public ActionResult Index()
        {
            return View(db.Paslaugos.ToList());
        }

        // GET: Paslaugas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paslauga paslauga = db.Paslaugos.Find(id);
            if (paslauga == null)
            {
                return HttpNotFound();
            }
            return View(paslauga);
        }

        // GET: Paslaugas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Paslaugas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,pavadinimas,aprasymas,kaina")] Paslauga paslauga)
        {
            if (ModelState.IsValid)
            {
                db.Paslaugos.Add(paslauga);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paslauga);
        }

        // GET: Paslaugas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paslauga paslauga = db.Paslaugos.Find(id);
            if (paslauga == null)
            {
                return HttpNotFound();
            }
            return View(paslauga);
        }

        // POST: Paslaugas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,pavadinimas,aprasymas,kaina")] Paslauga paslauga)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paslauga).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paslauga);
        }

        // GET: Paslaugas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paslauga paslauga = db.Paslaugos.Find(id);
            if (paslauga == null)
            {
                return HttpNotFound();
            }
            return View(paslauga);
        }

        // POST: Paslaugas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Paslauga paslauga = db.Paslaugos.Find(id);
            db.Paslaugos.Remove(paslauga);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viesbutis/Views/Paslaugas/Create.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Paslauga

@{
    ViewBag.Title = "Nauja";
}

<h2>Kurti naują paslaugą</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paslauga</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.pavadinimas, "Pavadinimas" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pavadinimas)
                @Html.ValidationMessageFor(model => model.pavadinimas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aprasymas, "Aprašymas", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aprasymas)
                @Html.ValidationMessageFor(model => model.aprasymas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kaina, "Kaina" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kaina)
                @Html.ValidationMessageFor(model => model.kaina)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kurti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į paslaugų sąrašą", "Index")
</div>

Viesbutis/Views/Paslaugas/Delete.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Paslauga

@{
    ViewBag.Title = "Ištrinti";
}

<h2>Ištrinti</h2>

<h3>Ar tikrai norite ištrinti šį įrašą?</h3>
<div>
    <h4>Paslauga</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> Pavadinimas </dt>
        <dd> @Html.DisplayFor(model => model.pavadinimas) </dd>
        <dt> Aprasymas </dt>
        <dd> @Html.DisplayFor(model => model.aprasymas) </dd>
        <dt> Kaina </dt>
        <dd> @Html.DisplayFor(model => model.kaina) </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ištrinti" class="btn btn-default" /> |
            @Html.ActionLink("Sugrįžti į sąrašą", "Index")
        </div>
    }
</div>

Viesbutis/Views/Paslaugas/Details.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Paslauga

@{
    ViewBag.Title = "Informacija";
}

<h2>Informacija apie paslaugą</h2>

<div>
    <h4>Paslauga</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> Pavadinimas </dt>
        <dd> @Html.DisplayFor(model => model.pavadinimas) </dd>
        <dt> Aprasymas </dt>
        <dd> @Html.DisplayFor(model => model.aprasymas) </dd>
        <dt> Kaina </dt>
        <dd> @Html.DisplayFor(model => model.kaina) </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Redaguoti", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Grįžti į rezervacijų sąrašą", "Index")
</p>

Viesbutis/Views/Paslaugas/Edit.cshtml
@model Viesbutis.Models.RezervacijaPosisteme.Paslauga

@{
    ViewBag.Title = "Redaguoti";
}

<h2>Redaguoti paslaugos informaciją</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paslauga</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.pavadinimas, "Pavadinimas" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pavadinimas)
                @Html.ValidationMessageFor(model => model.pavadinimas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aprasymas, "Aprašymas" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aprasymas)
                @Html.ValidationMessageFor(model => model.aprasymas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kaina, "Kaina" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kaina)
                @Html.ValidationMessageFor(model => model.kaina)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Išsaugoti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į paslaugų sąrašą", "Index")
</div>

Viesbutis/Views/Paslaugas/Index.cshtml
@model IEnumerable<Viesbutis.Models.RezervacijaPosisteme.Paslauga>

@{
    ViewBag.Title = "Paslaugos";
}

<h2>Paslaugos</h2>

<p>
    <input type="button" class="btn btn-default" value="Nauja" onclick="@("window.location.href='" + @Url.Action("Create", "Paslaugas") + "'");" />
</p>
<table class="table">
    <tr>
        <th> Pavadinimas </th>
        <th> Aprašymas </th>
        <th> Kaina </th>
        <th class="center"> Informacija </th>
        <th class="center"> Redaguoti </th>
        <th class="center"> Ištrinti </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.pavadinimas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.aprasymas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kaina)
        </td>
        <td class="center">
            <a href="@Url.Action("Details", new { id = item.ID })">
                <i class="glyphicon glyphicon-info-sign"></i>
            </a>
        </td>
        <td class="center">
            <a href="@Url.Action("Edit", new { id = item.ID })">
                <i class="glyphicon glyphicon-edit"></i>
            </a>
        </td>
        <td class="center">
            <a href="@Url.Action("Delete", new { id = item.ID })">
                <i class="glyphicon glyphicon-remove"></i>
            </a>
        </td>
    </tr>
}

</table>