Viesbutis/Models/KlientasPosisteme/Miestas.cs
using System;
using System.Collections.Generic;

namespace Viesbutis.Models.KlientasPosisteme
{
    public class Miestas
    {

        public int ID { get; set; }
        public string pavadinimas { get; set; }
        public int kodas { get; set; }
        public virtual ICollection<Klientas> Klientai { get; set; }
    }
}

Viesbutis/Models/KlientasPosisteme/ViewModels/MiestasViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Viesbutis.Models.KlientasPosisteme.ViewModels
{
    public class MiestasViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Pavadinimas")]
        public string pavadinimas { get; set; }

        [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Kodas")]
        public int kodas { get; set; }

        public virtual ICollection<Klientas> Klientai { get; set; }
    }
}

Viesbutis/Controllers/MiestasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Viesbutis.DAL;
using System.Net;
using Viesbutis.Models.KlientasPosisteme;
using System.Data;
using System.Data.Entity;
using Viesbutis.Models.KlientasPosisteme.ViewModels;

namespace Viesbutis.Controllers
{
    public class MiestasController : Controller
    {
        private ViesbutisContext _db = new ViesbutisContext();

        // returns the list of cities
        [Authorize(Roles = "Administratorius")]
        public ActionResult Index()
        {
            var miestai = _db.Miestai.OrderBy(x => x.pavadinimas);

            return View(miestai);
        }

        // returns the details of single city
        [Authorize(Roles = "Administratorius")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Miestas miestas = _db.Miestai.Find(id);
            if (miestas == null)
            {
                return HttpNotFound();
            }

            MiestasViewModel miestasViewModel = new MiestasViewModel() 
            {
                ID = miestas.ID,
                pavadinimas = miestas.pavadinimas,
                kodas = miestas.kodas
            };

            return View(miestasViewModel);
        }

        [Authorize(Roles = "Administratorius")]
        public ActionResult Create()
        {
            return View();
        }

        // creates a new city
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pavadinimas, kodas")]MiestasViewModel miestasViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Miestas miestas = new Miestas() 
                    {
                        pavadinimas = miestasViewModel.pavadinimas,
                        kodas = miestasViewModel.kodas
                    };
                    _db.Miestai.Add(miestas);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Įvyko klaida. Bandykite dar kartą.");
            }

            return View(miestasViewModel);
        }

        [Authorize(Roles = "Administratorius")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Miestas miestas = _db.Miestai.Find(id);
            if (miestas == null)
            {
                return HttpNotFound();
            }

            MiestasViewModel miestasViewModel = new MiestasViewModel() 
            {
                ID = miestas.ID,
                pavadinimas = miestas.pavadinimas,
                kodas = miestas.kodas
            };

            return View(miestasViewModel);
        }

        // edits the city information
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID, pavadinimas, kodas")]MiestasViewModel miestasViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Miestas miestas = new Miestas() 
                    {
                        ID = miestasViewModel.ID,
                        pavadinimas = miestasViewModel.pavadinimas,
                        kodas = miestasViewModel.kodas
                    };
                    _db.Entry(miestas).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Įvyko klaida. Bandykite dar kartą.");
            }

            return View(miestasViewModel);
        }

        [Authorize(Roles = "Administratorius")]
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Įvyko klaida. Bandykite dar kartą.";
            }

            Miestas miestas = _db.Miestai.Find(id);
            if (miestas == null)
            {
                return HttpNotFound();
            }

            MiestasViewModel miestasViewModel = new MiestasViewModel() 
            {
                ID = miestas.ID,
                pavadinimas = miestas.pavadinimas,
                kodas = miestas.kodas
            };

            return View(miestasViewModel);
        }

        // deletes the city
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Miestas miestas = _db.Miestai.Find(id);
                if (miestas.Klientai.Count() == 0)
                {
                    _db.Entry(miestas).State = EntityState.Deleted;
                    _db.SaveChanges();
                }
                else 
                {
                    ViewBag.ErrorMessage = "Miesto negalima ištrinti. Egzistuoja su juo susijusių vartotojų";
                    MiestasViewModel model = new MiestasViewModel 
                    {
                        ID = miestas.ID,
                        pavadinimas = miestas.pavadinimas,
                        kodas = miestas.kodas
                    };
                    return View(model);
                }
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Viesbutis/Views/Miestas/Create.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.MiestasViewModel

@{
    ViewBag.Title = "Naujas";
}

<h2>Kurti naują miestą</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Miestas</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.pavadinimas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.pavadinimas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pavadinimas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kodas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.kodas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.kodas)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kurti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į miestų sąrašą", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Viesbutis/Views/Miestas/Delete.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.MiestasViewModel

@{
    ViewBag.Title = "Ištrinti";
}

<h2>Ar tikrai norite ištrinti šį miestą?</h2>

<div>
    <h4>Miestas</h4>
    <p class="error">@ViewBag.ErrorMessage</p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pavadinimas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.pavadinimas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kodas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.kodas)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ištrinti" class="btn btn-default" /> |
            @Html.ActionLink("Grįžti į miestų sąrašą", "Index")
        </div>
    }
</div>

Viesbutis/Views/Miestas/Details.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.MiestasViewModel

@{
    ViewBag.Title = "Informacija";
}

<h2>Miesto informacija</h2>

<div>
    <h4>Miestas</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pavadinimas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.pavadinimas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kodas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.kodas)
        </dd>
    </dl>
</div>

<div>
    @Html.ActionLink("Grįžti į miestų sąrašą", "Index")
</div>

Viesbutis/Views/Miestas/Edit.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.MiestasViewModel

@{
    ViewBag.Title = "Redaguoti";
}

<h2>Redaguoti miesto informaciją</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Miestas</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.pavadinimas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.pavadinimas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pavadinimas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kodas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.kodas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.kodas)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Išsaugoti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į miestų sąrašą", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Viesbutis/Views/Miestas/Index.cshtml
@model IEnumerable<Viesbutis.Models.KlientasPosisteme.Miestas>

@{
    ViewBag.Title = "Miestai";
}

<style>
    .center {
        text-align: center;
    }
</style>

<h1>Miestai</h1>

<p>
    <input type="button" class="btn btn-default" value="Naujas" onclick="@("window.location.href='" + @Url.Action("Create", "Miestas") + "'");" />
</p>

<table class="table table-hover">
    <tr>
        <th class="col-md-1">
            Nr.
        </th>
        <th class="col-md-8">
            Pavadinimas
        </th>
        <th class="center">
            Informacija
        </th>
        <th class="center">
            Redaguoti
        </th>
        <th class="center">
            Ištrinti
        </th>
    </tr>

    @{
        int rowNumber = 1;
    }

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @string.Format("{0}.", rowNumber++)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pavadinimas)
            </td>
            <td class="center">
                <a href="@Url.Action("Details", new { id = item.ID })">
                    <i class="glyphicon glyphicon-info-sign"></i>
                </a>
            </td>
            <td class="center">
                <a href="@Url.Action("Edit", new { id = item.ID })">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </td>
            <td class="center">
                <a href="@Url.Action("Delete", new { id = item.ID })">
                    <i class="glyphicon glyphicon-remove"></i>
                </a>
            </td>
        </tr>
    }
</table>