Viesbutis/Models/KlientasPosisteme/Grupe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Viesbutis.Models.KlientasPosisteme
{
    public class Grupe
    {
        public int ID { get; set; }

        public string pavadinimas { get; set; }

        public double nuolaida { get; set; }

        public string aprasymas { get; set; }

        public virtual ICollection<Klientas> Klientai { get; set; }
    }
}

Viesbutis/Models/KlientasPosisteme/ViewModels/GrupeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Viesbutis.Models.KlientasPosisteme.ViewModels
{
    public class GrupeViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Pavadinimas")]
        public string pavadinimas { get; set; }

        [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Nuolaida")]
        public double nuolaida { get; set; }

        [Required(ErrorMessage = "Užpildykite laukelį"),
        Display(Name = "Aprašymas")]
        public string aprasymas { get; set; }

        public virtual ICollection<Klientas> Klientai { get; set; }
    }
}

Viesbutis/Controllers/GrupeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viesbutis.DAL;
using Viesbutis.Models.KlientasPosisteme;
using Viesbutis.Models.KlientasPosisteme.ViewModels;

namespace Viesbutis.Controllers
{
    public class GrupeController : Controller
    {
        private ViesbutisContext _db = new ViesbutisContext();

        // returns the list of groups
        [Authorize(Roles = "Administratorius")]
        public ActionResult Index()
        {
            var grupes = _db.Grupes.OrderBy(x => x.pavadinimas);

            return View(grupes);
        }

        // returns the details of single group
        [Authorize(Roles = "Administratorius")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Grupe grupe = _db.Grupes.Find(id);
            if (grupe == null)
            {
                return HttpNotFound();
            }

            GrupeViewModel grupeViewModel = new GrupeViewModel() 
            {
                ID = grupe.ID,
                pavadinimas = grupe.pavadinimas,
                nuolaida = grupe.nuolaida,
                aprasymas = grupe.aprasymas
            };

            return View(grupeViewModel);
        }

        [Authorize(Roles = "Administratorius")]
        public ActionResult Create()
        {
            return View();
        }

        // creates a new group
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pavadinimas, nuolaida, aprasymas")]GrupeViewModel grupeViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Grupe grupe = new Grupe() 
                    {
                        pavadinimas = grupeViewModel.pavadinimas,
                        nuolaida = grupeViewModel.nuolaida,
                        aprasymas = grupeViewModel.aprasymas
                    };
                    _db.Grupes.Add(grupe);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Įvyko klaida. Bandykite dar kartą.");
            }

            return View(grupeViewModel);
        }

        [Authorize(Roles = "Administratorius")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Grupe grupe = _db.Grupes.Find(id);
            if (grupe == null)
            {
                return HttpNotFound();
            }

            GrupeViewModel grupeViewModel = new GrupeViewModel() 
            {
                ID = grupe.ID,
                pavadinimas = grupe.pavadinimas,
                nuolaida = grupe.nuolaida,
                aprasymas = grupe.aprasymas
            };

            return View(grupeViewModel);
        }

        // edits the group information
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID, pavadinimas, nuolaida, aprasymas")]GrupeViewModel grupeViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Grupe grupe = new Grupe() 
                    {
                        ID = grupeViewModel.ID,
                        pavadinimas = grupeViewModel.pavadinimas,
                        nuolaida = grupeViewModel.nuolaida,
                        aprasymas = grupeViewModel.aprasymas
                    };
                    _db.Entry(grupe).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Įvyko klaida. Bandykite dar kartą.");
            }

            return View(grupeViewModel);
        }

        [Authorize(Roles = "Administratorius")]
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Įvyko klaida. Bandykite dar kartą.";
            }

            Grupe grupe = _db.Grupes.Find(id);
            if (grupe == null)
            {
                return HttpNotFound();
            }

            GrupeViewModel grupeViewModel = new GrupeViewModel() 
            {
                ID = grupe.ID,
                pavadinimas = grupe.pavadinimas,
                nuolaida = grupe.nuolaida,
                aprasymas = grupe.aprasymas
            };

            return View(grupeViewModel);
        }

        // deletes the group
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Grupe grupe = _db.Grupes.Find(id);
                if (grupe.Klientai.Count() == 0)
                {
                    _db.Entry(grupe).State = EntityState.Deleted;
                    _db.SaveChanges();
                }
                else
                {
                    ViewBag.ErrorMessage = "Grupės negalima ištrinti. Egzistuoja su ja susijusių vartotojų";
                    GrupeViewModel model = new GrupeViewModel
                    {
                        ID = grupe.ID,
                        pavadinimas = grupe.pavadinimas,
                        nuolaida = grupe.nuolaida,
                        aprasymas = grupe.aprasymas
                    };
                    return View(model);
                }
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Viesbutis/Views/Grupe/Create.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.GrupeViewModel

@{
    ViewBag.Title = "Nauja";
}

<h2>Kurti naują kliento grupę</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kliento grupė</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.pavadinimas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.pavadinimas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pavadinimas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nuolaida, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.nuolaida, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nuolaida)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aprasymas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.aprasymas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.aprasymas)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kurti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į kliento grupių sąrašą", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Viesbutis/Views/Grupe/Delete.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.GrupeViewModel

@{
    ViewBag.Title = "Ištrinti";
}

<h2>Ar tikrai norite ištrinti šią kliento grupę?</h2>

<div>
    <h4>Kliento grupė</h4>
    <p class="error">@ViewBag.ErrorMessage</p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pavadinimas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.pavadinimas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nuolaida)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nuolaida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aprasymas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.aprasymas)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ištrinti" class="btn btn-default" /> |
            @Html.ActionLink("Grįžti į kliento grupių sąrašą", "Index")
        </div>
    }
</div>

Viesbutis/Views/Grupe/Details.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.GrupeViewModel

@{
    ViewBag.Title = "Informacija";
}

<h2>Kliento grupės informacija</h2>

<div>
    <h4>Kliento grupė</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pavadinimas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.pavadinimas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nuolaida)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nuolaida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aprasymas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.aprasymas)
        </dd>
    </dl>
</div>

<div>
    @Html.ActionLink("Grįžti į kliento grupių sąrašą", "Index")
</div>

Viesbutis/Views/Grupe/Edit.cshtml
@model Viesbutis.Models.KlientasPosisteme.ViewModels.GrupeViewModel

@{
    ViewBag.Title = "Redaguoti";
}

<h2>Redaguoti kliento grupės informaciją</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kliento grupė</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.pavadinimas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.pavadinimas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pavadinimas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nuolaida, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.nuolaida, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nuolaida)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aprasymas, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.aprasymas, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.aprasymas)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Išsaugoti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į kliento grupių sąrašą", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Viesbutis/Views/Grupe/Index.cshtml
@model IEnumerable<Viesbutis.Models.KlientasPosisteme.Grupe>

@{
    ViewBag.Title = "Kliento grupės";
}

<style>
    .center {
        text-align: center;
    }
</style>

<h1>Kliento grupės</h1>

<p>
    <input type="button" class="btn btn-default" value="Nauja" onclick="@("window.location.href='" + @Url.Action("Create", "Grupe") + "'");" />
</p>

<table class="table table-hover">
    <tr>
        <th class="col-md-1">
            Nr.
        </th>
        <th class="col-md-8">
            Pavadinimas
        </th>
        <th class="center">
            Informacija
        </th>
        <th class="center">
            Redaguoti
        </th>
        <th class="center">
            Ištrinti
        </th>
    </tr>

    @{
        int rowNumber = 1;
    }

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @string.Format("{0}.", rowNumber++)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pavadinimas)
            </td>
            <td class="center">
                <a href="@Url.Action("Details", new { id = item.ID })">
                    <i class="glyphicon glyphicon-info-sign"></i>
                </a>
            </td>
            <td class="center">
                <a href="@Url.Action("Edit", new { id = item.ID })">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </td>
            <td class="center">
                <a href="@Url.Action("Delete", new { id = item.ID })">
                    <i class="glyphicon glyphicon-remove"></i>
                </a>
            </td>
        </tr>
    }
</table>